name: CI/CD Inovatech EKS

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

env:
  AWS_REGION: us-east-1
  ECR_REPO_FRONTEND: tienda-frontend
  ECR_REPO_VENTAS: tienda-ventas
  ECR_REPO_DESPACHOS: tienda-despachos

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      # ---------- AWS ----------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      # ---------- LOGIN ECR ----------
      - name: Login ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      # ---------- FRONTEND ----------
      - name: Build FRONTEND
        run: |
          cd front_despacho
          docker build -t $ECR_REPO_FRONTEND:$IMAGE_TAG .

      # ---------- VENTAS ----------
      - name: Build VENTAS
        run: |
          cd back-Ventas_SpringBoot/Springboot-API-REST
          docker build -t $ECR_REPO_VENTAS:$IMAGE_TAG .

      # ---------- DESPACHOS ----------
      - name: Build DESPACHOS
        run: |
          cd back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
          docker build -t $ECR_REPO_DESPACHOS:$IMAGE_TAG .

      # ---------- PUSH ----------
      - name: Push images
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker tag $ECR_REPO_FRONTEND:$IMAGE_TAG $REGISTRY/$ECR_REPO_FRONTEND:$IMAGE_TAG
          docker tag $ECR_REPO_VENTAS:$IMAGE_TAG $REGISTRY/$ECR_REPO_VENTAS:$IMAGE_TAG
          docker tag $ECR_REPO_DESPACHOS:$IMAGE_TAG $REGISTRY/$ECR_REPO_DESPACHOS:$IMAGE_TAG

          docker push $REGISTRY/$ECR_REPO_FRONTEND:$IMAGE_TAG
          docker push $REGISTRY/$ECR_REPO_VENTAS:$IMAGE_TAG
          docker push $REGISTRY/$ECR_REPO_DESPACHOS:$IMAGE_TAG

      # ---------- KUBECTL ----------
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.29.0

      - name: Configure EKS
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name ${{ secrets.EKS_CLUSTER_NAME }}

      # ---------- DEPLOY ----------
      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/

          kubectl set image deployment/ventas ventas=$REGISTRY/$ECR_REPO_VENTAS:$IMAGE_TAG
          kubectl set image deployment/despachos despachos=$REGISTRY/$ECR_REPO_DESPACHOS:$IMAGE_TAG
          kubectl set image deployment/frontend frontend=$REGISTRY/$ECR_REPO_FRONTEND:$IMAGE_TAG

          kubectl rollout status deployment/ventas
          kubectl rollout status deployment/despachos
          kubectl rollout status deployment/frontend